FactbirdHQ/atat

.github/workflows/ci.yml, Cargo.toml, README.md, examples/common/command.rs, examples/cortex-m-rt.rs, src/client.rs, src/lib.rs, src/parser.rs, src/tests.rs, src/traits.rs
This sets up a GitHub workflow that does the following:
- Build the library on ARMv7 with Rust stable
- Build the examples on ARMv7 with Rust stable
- Run tests with Rust stable
- Run clippy
If you like rustfmt, I could even add a rustfmt check step.
There are also some other commits in here to make the tests actually pass. For example, the parser used the `log` crate which requires `std`.
=> Set up CI, ensure that crate is no_std

atat/examples/cortex-m-rt.rs, atat/examples/rtfm.rs, atat/src/client.rs, atat/src/ingress_manager.rs, atat_derive/src/cmd.rs
* Fixed handling multiline responses, and added a test for it. 
* Bumb `get_line()` length from `U64` to `U128`.
* Change `parse_at` to `digest`
Fixes https://github.com/dbrgn/espresso/issues/1
=> Fixed handling multiline responses

serde_at/src/de/mod.rs
Correctly handle whitespaces between command an params, eg '+CWMODE_CUR:1' vs 'CWMODE_CUR: 1'
Fixes #29
=> Correctly handle whitespaces between command an params

atat/src/ingress_manager.rs
Log incoming messages on DEBUG level once they're complete (both echo responses and URCs).
Invalid messages are only visible in TRACE level.
Logs filtered by DEBUG+ level can look like this:
```
[2020-03-14T22:17:35Z DEBUG atat::client] Sending command: "AT\r\n"
[2020-03-14T22:17:35Z DEBUG atat::ingress_manager] Received response: Ok("")
[2020-03-14T22:17:35Z DEBUG atat::client] Sending command: "AT+GMR\r\n"
[2020-03-14T22:17:35Z DEBUG atat::ingress_manager] Received response: Ok("AT version:1.1.0.0(May 11 2016 18:09:56)\r\nSDK version:1.5.4(baaeaebb)\r\ncompile time:May 20 2016 15:08:19")
[2020-03-14T22:17:35Z DEBUG atat::client] Sending command: "AT+RST\r\n"
[2020-03-14T22:17:35Z DEBUG atat::ingress_manager] Received response: Ok("")
```
Based on #27, merge that first! (That's why this …
=> Improved ingress logging

atat/src/client.rs, atat/src/ingress_manager.rs, atat/src/lib.rs, atat/src/queues.rs
Some refactoring. The types spread across the modules were a bit difficult to grasp.
=> Extract queue types into separate module

atat/examples/cortex-m-rt.rs, atat/examples/rtfm.rs, atat/src/client.rs, atat/src/ingress_manager.rs, atat/src/lib.rs, atat/src/queues.rs
This was very tricky, but here's a suggestion for how custom URC handlers could be implemented.
Unfortunately this requires a type parameter for the `IngressManager` even if no custom URC handler is specified :confused: I added a dummy `DefaultUrcHandler` that can be used in those cases. We could offer some wrapper types that make this easier for the users by using `DefaultUrcHandler` by default.
PR might need some cleanup, but what do you think about the general direction? Best place to see how it works is the `custom_urc_handler` test.
Attempts to fix #33.
This also bumps the max size for URCs to 256 bytes.
=> Add support for custom URC matchers

atat/examples/cortex-m-rt.rs, atat/examples/rtfm.rs, atat/src/client.rs, atat/src/ingress_manager.rs, atat/src/lib.rs
- The IngressManager now has a default type parameter for the
UrcMatcher, this lets you omit the parameter in some cases
- There are two methods on the `IngressManager`: `new` and
`with_custom_urc_matcher`. This way the user does not need to provide
a type parameter for the `UrcMatcher` at all when not using this
feature, Rust can automatically derive the type.
- To improve ergonomics on the top-level, the `atat::new` factory
function has now been replaced with a `ClientBuilder`.
Thanks @gandro for providing the API design idea with the default type parameter!
=> Create ClientBuilder and hide UrcMatcher type

Cargo.lock, Cargo.toml, README.md, atat/Cargo.toml, atat/examples/common/general/types.rs, atat/examples/common/mod.rs, atat/src/client.rs, atat/src/ingress_manager.rs, atat/src/lib.rs, atat/src/queues.rs, atat/src/traits.rs, atat_derive/Cargo.toml, atat_derive/src/cmd.rs, atat_derive/src/urc.rs, serde_at/Cargo.toml, serde_at/src/de/mod.rs, serde_at/src/de/seq.rs
Refactor underlying receive buffer from String to Vec<u8>, to accomodate non-ascii character transfers (eg. binary data)
Fixes #39
=> Refactor ingress buffer to Vec<u8>

.github/workflows/grcov.yml, README.md, atat/Cargo.toml, atat/src/client.rs, atat/src/error.rs, atat/src/ingress_manager.rs, atat/src/lib.rs, serde_at/Cargo.toml
This PR will add support for defmt (https://defmt.ferrous-systems.com/introduction.html) logging.
It introduces a couple of new feature flags, and changes the old logging flag:
- `log-logging`: Disabled by default. Enable log statements on various log levels to aid debugging. Powered by `log`.
- `defmt-default`: Disabled by default. Enable log statements at INFO, or TRACE, level and up, to aid debugging. Powered by `defmt`.
- `defmt-trace`: Disabled by default. Enable log statements at TRACE level and up, to aid debugging. Powered by `defmt`.
- `defmt-debug`: Disabled by default. Enable log statements at DEBUG level and up, to aid debugging. Powered by `defmt`.
- `defmt-info`: Disabled by default. Enable log statements at INFO level and up, to aid debugging. Powered by `defmt`.
- …
=> Add support for defmt logging

atat/src/lib.rs, atat_derive/src/cmd.rs, atat_derive/src/len.rs
When deriving AtatCmd, I get an error because my app does not need `serde_at` directly:
```
19 | #[derive(Clone, AtatCmd)]
|                 ^^^^^^^ use of undeclared type or module `serde_at`
|
= note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
I think this is caused by the `#[inline]` in the macro directly pasting the code. By re-exporting `serde_at` in `atat`, we can get around this.
I'm not well versed in idiomatic rust, so hopefully this is a good way to fix this!
=> Fix derive(AtatCmd) missing serde_at import

.github/workflows/test.yml, atat/Cargo.toml, serde_at/Cargo.toml, serde_at/src/de/mod.rs, serde_at/src/lib.rs, serde_at/src/ser/mod.rs
I get 15 errors trying to compile `serde_at` when using std, because serde defines its internal type `StdError` as `std::error::Error`, which serde_at does not implement. Here's an example:
```
error[E0277]: the trait bound `ser::Error: serde::de::StdError` is not satisfied
--> /home/mon/.cargo/registry/src/github.com-aaa/serde_at-0.4.3/src/ser/mod.rs:501:18
|
501 |     type Error = Error;
|                  ^^^^^ the trait `serde::de::StdError` is not implemented for `ser::Error`
```
By adding an optional `std` feature which implements this trait, compilation is successful!
=> Add "std" feature to fix compile when using std

.github/workflows/codecov.yml, atat/src/lib.rs, serde_at/src/de/mod.rs, serde_at/src/de/seq.rs, serde_at/src/lib.rs
Wrapper for deserializing a Vector of bytes like fx "+UUWLE:32AB6A7A4044".
Primarily done to parse bssid for [ublox-short-range-rs](https://github.com/BlackbirdHQ/ublox-short-range-rs/).
But this is kind of a catch all for any Non comma separated value in any AT command.
=> Feature/Byte Vec Deserialize Wrapper

atat/src/derive.rs, atat/src/ingress_manager.rs, atat/src/lib.rs, atat/src/traits.rs, atat_derive/src/urc.rs, serde_at/src/de/map.rs, serde_at/src/de/mod.rs, serde_at/src/de/seq.rs, serde_at/src/ser/mod.rs
This will correctly handle multi-line response AT commands using `heapless::Vec`
Eg.
```
> AT+CGACT?
< +CGACT: <cid>,<status>
< +CGACT: <cid>,<status>
...
< OK
```
Where `+CGACT: <cid>,<status>` can be repeated zero or more times, with a new cid,status pair.
fixes #63
=> Implement support for multi-line responses

.github/workflows/codecov.yml, .github/workflows/lint.yml, .github/workflows/test.yml, README.md, atat/Cargo.toml, atat/examples/cortex-m-rt.rs, atat/src/client.rs, atat/src/digest.rs, atat/src/error.rs, atat/src/helpers.rs, atat/src/ingress_manager.rs, atat/src/lib.rs, atat/src/traits.rs
This is a WIP PR to reintroduce the `log-logging` feature flag (as has been discussed in #86 ).
I first looked at the changes from #80 but then decided to introduce a new `LossyStr` type that's wrapping `&[u8]` and implementing formatting as a str (if possible) for both defmt and core::fmt::Debug. This way, there's no need to use feature flags when calling `atat_log` with a byte slice as param.
I haven't fully tested the code yet, but I wanted to open the PR to gather feedback.
Have a great day ;-)
=> reimplement log-logging feature

.github/codecov.yml, .github/workflows/codecov.yml, atat/src/client.rs, atat/src/helpers.rs, atat/src/traits.rs, atat_derive/src/cmd.rs
Change AtatCmd to be associated consts rather than functions:
- `can_abort`
- `max_timeout_ms`
- `force_receive_state`
- `expects_response_code` 
Fixes #88
=> Change parameters of AtatCmd to associated consts

atat_derive/src/cmd.rs
Fix issue where zero length at commands results on a heapless::String of length 0, not allowed in const-generics version
=> Fix heapless string becoming zero length

.github/workflows/ci.yml, serde_at/Cargo.toml, serde_at/src/de/mod.rs, serde_at/src/lib.rs, serde_at/src/ser/mod.rs
Implement `serde::{ser/de}::StdError` for both `no_std` & `std`, as it is exported in both cases.
Fixes #104
=> Implement serde::StdError for both no_std & std

.github/workflows/ci.yml, atat/Cargo.toml
Then dev-dependencies (examples) are built only for thumbv7em-none-eabihf.
This fixed #104 for me.
Now I can run `cargo test --tests` and everything builds and runs.
Without this I got:
```
Compiling stm32l4 v0.12.1
Compiling stm32l4xx-hal v0.5.0 (https://github.com/MathiasKoch/stm32l4xx-hal?branch=enhancement/prepare-embedded-hal-1.0#28490318)
LLVM ERROR: Global variable '__INTERRUPTS' has an invalid section specifier '.vector_table.interrupts': mach-o section specifier requires a segment and section separated by a comma.
error: could not compile `stm32l4`
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Which makes sense, because those libs cannot be built for x86.
=> use target.thumbv7em-none-eabihf.dev-dependencies

atat/Cargo.toml, atat/examples/cortex-m-rt.rs, atat/examples/rtic.rs, atat/src/builder.rs, atat/src/client.rs, atat/src/lib.rs
This is needed to work with: https://github.com/BlackbirdHQ/ublox-cellular-rs/pull/54 where `embedded-time` is replaced by `fugit`.
=> Use `fugit` for timing

atat/src/client.rs, atat/src/digest.rs, atat/src/fmt.rs, atat/src/helpers.rs, atat/src/ingress_manager.rs, atat/src/lib.rs
This PR replaces `atat_log` macro with [embassy/fmt.rs](https://github.com/embassy-rs/embassy/blob/master/embassy/src/fmt.rs).
Idea is to start using `fmt.rs` also in `ublox-sockets` and `ublox-cellular`. Then logging would be the same in all companion crates and this makes debugging easier on x86 platforms that do not have native `defmt` support.
PS: Unfortunately `fmt.rs` cannot be turned into separate crate, therefore it must be just copy-pasted to use it.
=> Improve logging macros

.github/workflows/ci.yml, atat/Cargo.toml, atat/examples/cortex-m-rt.rs, atat/examples/rtic.rs, atat/src/builder.rs, atat/src/client.rs, atat/src/lib.rs, serde_at/src/de/mod.rs
I've moved `Clocks` in separate crate as it's too hard to implement it in HALs during this part of `atat`.
In other side it can't be a part of `embedded-hal` as `fugit` primitives are only one of possible solutions.
=> update deps, use fugit_timer::Timer instead of Clocks

README.md
How to finish non-working projects: Wait long enough until someone comes along and implements what you need 😂
I archived espresso, since esp-at-nal by @marius-meissner works much better already.
=> README: Remove espresso, superseded by esp-at-nal

atat/src/client.rs, atat_derive/src/urc.rs
The current implementation of the URC parser expects the format "code:" (including a colon). For the simcom sim800 modem there are URC's such as "CONNECT OK" without a colon. This PR lets the parser match on the entire response in case a colon is not found.
=> Support URC's without a colon

atat/src/digest.rs, atat/src/error/mod.rs, serde_at/src/de/mod.rs
The digest should not continue to lower priority cases if the parser returns incomplete.
This fixes #140
=> Fix digest continuation bug

serde_at/src/lib.rs, serde_at/src/ser/mod.rs
`mem::MaybeUninit::uninit().assume_init()` is almost always UB.
(Caught by Miri)
=> Avoid UB due to uninitialized memory in `serde_at`

atat/src/digest.rs, atat/src/ingress.rs
The reason for this change is that e.g. the prompt which can be any of ">" or "> " (with space).
If the device uses "> " as prompt, and if we digest the partial prompt ">", then there will be a space in the ingress buffer for the next digest. This space should be trimmed.
=> Ensure that any leading leftover space is trimmed in digester

.vscode/settings.json, atat/src/lib.rs
I want to use `atat` with an `rtic v2` project instead of embassy. Therefore I implemented my own async Client that does not depend on `embassy_time`. In order to have my own specific client implementation outside of the `atat` crate I need to access response_channel. So I have made it public. 
I feel like this is preferable over having many specific client implementations in `atat`.
=> Enable external client implementations by making response_channel pub

serde_at/src/lib.rs, serde_at/src/ser/enum_.rs, serde_at/src/ser/mod.rs, serde_at/src/ser/struct_.rs
This change removes the buffer size generic on the serializer.
For my firmware that uses the simcom grps driver [here](https://github.com/rmja/chip-drivers/tree/master/cellular/simcom-gprs), the build size is reduced from:
```
text    data     bss     dec     hex filename
318432     120   52888  371440   5aaf0 urcc
```
to
```
text    data     bss     dec     hex filename
316732     120   52888  369740   5a44c urcc
```
=> Add at serializer to_slice

atat/src/digest.rs, atat/src/ingress.rs
Added documentation to the `Parser` trait and made some `AtatIngress` documentation more specific.
=> Document `Parser`

atat_derive/src/len.rs
`rust-analyzer` complains about this.
=> fix const e_len upper case

atat/src/digest.rs
This follows the format specified at https://docs.rs/atat/latest/atat/digest/struct.AtDigester.html :
- `…<URC>\r\n…`
- `…<URC>:<PARAMETERS>\r\n…`
The previous version was too lenient so if a response contained some of the URC token e.g. `ABCD` for URC `ABC`, this response gets matched as a URC.
=> fix URC parse colon

atat/src/lib.rs
This exposes currently internal error types with are used inside the main error type and accessible to the user.
This is need for example when entering as PIN to modem and repeat the command on errors other then IncorrectPassword and/or SimPuk (I often have to deal with SIM cards that fail at first try on this command on my modem).
Fixes https://github.com/BlackbirdHQ/atat/issues/176
=> expose currently internal error types

serde_at/src/de/mod.rs
Partly fixes issue https://github.com/BlackbirdHQ/atat/issues/180
When a response string does contain empty argument `,,` it should be parsed to `Option::None` instead of failing on it.
Example response string containing such arguments: 
`+CMGR: \"REC UNREAD\",\"+48123456789\",,\"23/11/21,13:31:39+04\"\r\nINFO`
=> fix parsing empty arguments to option none

serde_at/src/de/mod.rs, serde_at/src/de/seq.rs
I think I have here something for issue https://github.com/BlackbirdHQ/atat/issues/180 that doesn't fell like a huge hack.
Still probably a hack but a hope a small one.
It misuses  `fields` attribute from `deserialize_struct()`, saves it count in the Deserializer. 
Then SeqAccess does count how many fields it already parsed, if it hits the branch that no `,` are present anymore and the count of parsed fields is exactly one less then the expected count of fields to parse it sets a flag in the  Deserializer `is_trailing_parsing` to indicate that `parse_str` or `parse_bytes`  should now just take everything left and try to parse it.
This does seam to work fine for my use case, but I bet it still has some edge cases where it might not work.
Doesn't seam to break any other tests and I add a …
=> fix parsing trailing message content from CMGR command

atat/src/asynch/client.rs, atat/src/blocking/client.rs
I can not think of a reason why Client pub new couldn't be public.
With this change an user can full create a ResponseChannel, UrcChannel, Ingress and the Client by them self.
This allows doing something like that:
```rust
static RESPONSE_CHANNEL: ResponseChannel<INGRESS_BUF_SIZE> = ResponseChannel::new();
static URC_CHANNEL: UrcChannel<Urc, URC_CAPACITY, URC_SUBSCRIBERS> = UrcChannel::new();
static DIGESTER: DefaultDigester<Urc> = DefaultDigester::<Urc>::default();
let ingress = Box::new(Ingress::new(
DefaultDigester::<Urc>::default(),
RESPONSE_CHANNEL.publisher().unwrap(),
URC_CHANNEL.publisher(),
));
let client = asynch::Client::new(
tx,
&RESPONSE_CHANNEL,
atat::Config::default().cmd_cooldown(core::time::Duration::from_millis(5).try_into().unwrap()),
);
```
The advantage in that is we …
=> make Client public to allow tighter control over how it is created

serde_at/Cargo.toml, serde_at/src/de/length_delimited.rs, serde_at/src/de/mod.rs
This PR adds a struct to help parsing length delimited payloads. There are currently a few assumptions:
- The length delimited payload is at the end of a response. This is because I have not found a way to communicate back the number of eaten bytes used for parsing to the Deserializer.
- The payload is "quoted" but the quotes do not count for the length. This is how I have seen it on Quectel modems.
I still need to do more tests but I wouldn't mind some early feedback.
- I have commandeered `deserialize_tuple` as it was not used. I couldn't use `deserialize_bytes` as it clips the slice at the first `,`.
- In `deserialize_tuple` we set ` self.index = self.slice.len();` which causes `LengthDelimited` to only work at the end of the response.
=> Add LengthDelimited struct to parse <len, "bytes"> payloads.

serde_at/src/de/mod.rs
Now I hit unreachable!() on deserialize_byte_buf.
This PR adds support for deserialize_byte_buf when alloc feature is enabled.
Similar too https://github.com/BlackbirdHQ/atat/pull/192
=> add support for deserialize_byte_buf when alloc is enabled

atat/src/ingress.rs, atat/src/lib.rs, atat/src/urc_channel.rs, examples/src/bin/embassy.rs, examples/src/bin/std-tokio.rs
This also removes the export of the ResponsePublisher/Subscriber as they are no longer needed. And, the AtatUrcChannel trait is removed. The methods are simply added to the UrcChannel struct
=> Let Ingress take channel instead of publisher's and cleanup UrcChannel

atat/src/derive.rs, atat_derive/src/cmd.rs, atat_derive/src/lib.rs, atat_derive/src/parse.rs
While still struggling with parsing QIRD response from Quactel BG95 for all possible use case where the binary payload does contain bytes that are equal too \n or \r or other whitespace or even comma with was causing a lot of problems too I come to the conclusion that the response is just to obscure for serde_at and I implemented `AtatCmd` trait myself overriding the parse function to not use serde_at at all for this one outlier. 
But that does lead to a lot more boilerplate in my code since now I need to implement `AtatLen` and all other trait functions for that structs. With this PR this can be avoided and a user can just provide a custom parse function with the parse argument on the `at_cmd` attributes when using `AtatCmd` derive
=> add custom parse function to AtatCmd derive

atat/src/digest.rs
This is required for AT commands where the modem responds with
`CONNECT <NUM>` followed by `NUM` bytes.
The tests still work so I am not sure if there was a specific reason for 
```rust
take_until_including("\r\nCONNECT"),
recognize(take_until_including("\r\n")),
```
vs
```rust
take_until_including("\r\nCONNECT\r\n"),
```
Do we in some cases expect bytes between `CONNECT` and `\r\n` that we want to discard?
=> Do not recognize CONNECT <NUM> as a success response.

atat/src/digest.rs, atat/src/ingress.rs, atat_derive/src/lib.rs, atat_derive/src/parse.rs, atat_derive/src/urc.rs, serde_at/src/de/mod.rs
Add an optional parse fn to the at_urc field attribute of AtatUrc, that allows specifying a custom nom function to be used during digest. This allows doing stricter checks for cases where responses are hard to distinguish from URCs.
Fixes https://github.com/BlackbirdHQ/atat/issues/179 (See example of a stricter custom CxREG parser fn in tests (`fn custom_cxreg_parse`))
=> feature(*): Add option for custom parse fn in AtatUrc

atat/src/ingress.rs
=> Protect against busy-loop in Ingress::read_from

atat/src/digest.rs
Closes #213 
**Please carefully review especially the 2nd commit. I'm not sure if this change causes unintended consequences!**
=> Fix URC parsing issues

atat/src/blocking/client.rs, serde_at/src/de/mod.rs
While parsing the CGMI of my device (SIM7020), I've noticed that I was getting a lot of parsing errors.  
After digging deeper, I've discovered that the parsing errors were actually `EofWhileParsingString` errors.  
Finally, I've discovered why: my manufacturer string looked like this:
```
SIMCOM_Ltd
```
And this was breaking at the `_`, because it's not considered alphanumeric.
My fix here is to allow all ASCII characters >= 32 (space + printable characters).
The only non-printable character included is `DEL` (127) - but it shouldn't be a big deal.
---
```rust
match client.send(&common::GetManufacturerId{}).await {
Ok(resp) => {
info!("Manufacturer ID OK: resp={:?}", resp.id.as_str());
}
Err(e) => {
println!("Error: {:?}", e);
}
}
```
Before my fix:
```
DEBUG Response: "SIMCOM_Ltd"
Error …
```
=> fix(serde_at): deserialize _

examples/Cargo.toml, examples/src/bin/std-tokio-mock.rs
When playing around with `atat` I find it useful to "mock" a device to better understand how e.g. the command parsing works. I thought maybe it might be useful for somebody else. :-)
The example also shows how a CME error is handled by DefaultDigester.
=> add example of mocked device using tokio

serde_at/src/de/length_delimited.rs, serde_at/src/de/mod.rs
Small improvement to the feature added here: https://github.com/FactbirdHQ/atat/pull/186
My use case is a URC of the Quectel BG95:
In "direct push mode" the modem forwards incoming socket data via URC with this format:
`+QIURC: "recv",<connectID>,<currectrecvlength><CR><LF><data>`
The `LengthDelimited` currently does not support a line break between the length and data - or any other separator than an comma.
This PR changes two things:
- instead of looking for a comma after the length, look for anything that is not a digit
- add a custom length parameter to skip over arbitrary separators
The length parameter defaults to 1, so this should not be a breaking change.
Draft PR for now, because I could not test this on an actual device yet.
=> add custom separator support to LengthDelimited
